// GENERATED by tools/gen_consent_display_table.py -- DO NOT EDIT (A8-R1 clause 5; m-3 addendum 8 rev8).
// Unicode version: 15.0.0 (pinned; a version bump is a design act at m-3's seat, never a regeneration).
// class = General_Category in {Cf, Zl, Zp} UNION Default_Ignorable_Code_Point, as sorted merged ranges.
// input sha256: 806e9aed65037197f1ec85e12be6e8cd870fc5608b4de0fffd990f689f376a73  UnicodeData.txt
// input sha256: d367290bc0867e6b484c68370530bdd1a08b6b32404601b8c7accaf83e05628d  DerivedCoreProperties.txt
// generator sha256: 8ef548490b15395640ef0c93ebb49e6f2f98a1dc1955a3f413ab24c444b62449
// members: 4208  ranges: 25
#pragma once
#include <array>
#include <cstddef>
namespace biv::cli {
struct ConsentDisplayRange { char32_t first; char32_t last; };
inline constexpr std::array<ConsentDisplayRange, 25> kConsentDisplayActive{{
    {0x00AD, 0x00AD},
    {0x034F, 0x034F},
    {0x0600, 0x0605},
    {0x061C, 0x061C},
    {0x06DD, 0x06DD},
    {0x070F, 0x070F},
    {0x0890, 0x0891},
    {0x08E2, 0x08E2},
    {0x115F, 0x1160},
    {0x17B4, 0x17B5},
    {0x180B, 0x180F},
    {0x200B, 0x200F},
    {0x2028, 0x202E},
    {0x2060, 0x206F},
    {0x3164, 0x3164},
    {0xFE00, 0xFE0F},
    {0xFEFF, 0xFEFF},
    {0xFFA0, 0xFFA0},
    {0xFFF0, 0xFFFB},
    {0x110BD, 0x110BD},
    {0x110CD, 0x110CD},
    {0x13430, 0x1343F},
    {0x1BCA0, 0x1BCA3},
    {0x1D173, 0x1D17A},
    {0xE0000, 0xE0FFF},
}};
inline constexpr bool consent_display_active(char32_t scalar) noexcept {
  std::size_t lo = 0, hi = kConsentDisplayActive.size();
  while (lo < hi) {
    const std::size_t mid = lo + (hi - lo) / 2;
    if (scalar < kConsentDisplayActive.at(mid).first) hi = mid;
    else if (scalar > kConsentDisplayActive.at(mid).last) lo = mid + 1;
    else return true;
  }
  return false;
}
}  // namespace biv::cli
