#!/usr/bin/env python3
# usage: gen_consent_display_table.py <UnicodeData.txt> <DerivedCoreProperties.txt> <inputs.sha256> > consent_display_table.hpp
# The A8-R1 clause-5 class at Unicode 15.0.0: General_Category in {Cf, Zl, Zp} UNION Default_Ignorable_Code_Point, emitted as sorted,
# merged [first, last] ranges of char32_t. Deterministic: same inputs -> same bytes. The header records the Unicode version, both input
# digests (read from <inputs.sha256>, which the caller produced with shasum -a 256) and this generator's own sha256.
import hashlib, re, sys
ud, dcp, digests = sys.argv[1], sys.argv[2], sys.argv[3]
first = open(dcp, encoding="utf-8").readline().rstrip("\n")
if first != "# DerivedCoreProperties-15.0.0.txt":
    sys.exit("STOP: DerivedCoreProperties header is not 15.0.0: %r" % first)
members = set()
# UnicodeData: field 2 = General_Category; ranges are given as "<..., First>" / "<..., Last>" pairs
pending_first = None
for line in open(ud, encoding="utf-8"):
    f = line.rstrip("\n").split(";")
    if len(f) < 3:
        continue
    cp, name, gc = int(f[0], 16), f[1], f[2]
    if name.endswith(", First>"):
        pending_first = (cp, gc); continue
    if name.endswith(", Last>"):
        lo, gc0 = pending_first; pending_first = None
        if gc0 in ("Cf", "Zl", "Zp"):
            members.update(range(lo, cp + 1))
        continue
    if gc in ("Cf", "Zl", "Zp"):
        members.add(cp)
for line in open(dcp, encoding="utf-8"):
    m = re.match(r"^([0-9A-F]{4,6})(?:\.\.([0-9A-F]{4,6}))?\s*;\s*Default_Ignorable_Code_Point\b", line)
    if m:
        lo = int(m.group(1), 16); hi = int(m.group(2), 16) if m.group(2) else lo
        members.update(range(lo, hi + 1))
if not members:
    sys.exit("STOP: empty class")
ranges = []
for cp in sorted(members):
    if ranges and cp == ranges[-1][1] + 1:
        ranges[-1][1] = cp
    else:
        ranges.append([cp, cp])
self_digest = hashlib.sha256(open(sys.argv[0], "rb").read()).hexdigest()
digest_lines = [ln.strip() for ln in open(digests, encoding="utf-8") if ln.strip()]
out = []
out.append("// GENERATED by tools/gen_consent_display_table.py -- DO NOT EDIT (A8-R1 clause 5; m-3 addendum 8 rev8).")
out.append("// Unicode version: 15.0.0 (pinned; a version bump is a design act at m-3's seat, never a regeneration).")
out.append("// class = General_Category in {Cf, Zl, Zp} UNION Default_Ignorable_Code_Point, as sorted merged ranges.")
for ln in digest_lines:
    out.append("// input sha256: " + ln)
out.append("// generator sha256: " + self_digest)
out.append("// members: %d  ranges: %d" % (len(members), len(ranges)))
out.append("#pragma once")
out.append("#include <array>")
out.append("#include <cstddef>")
out.append("namespace biv::cli {")
out.append("struct ConsentDisplayRange { char32_t first; char32_t last; };")
out.append("inline constexpr std::array<ConsentDisplayRange, %d> kConsentDisplayActive{{" % len(ranges))
for lo, hi in ranges:
    out.append("    {0x%04X, 0x%04X}," % (lo, hi))
out.append("}};")
out.append("inline constexpr bool consent_display_active(char32_t scalar) noexcept {")
out.append("  std::size_t lo = 0, hi = kConsentDisplayActive.size();")
out.append("  while (lo < hi) {")
out.append("    const std::size_t mid = lo + (hi - lo) / 2;")
out.append("    if (scalar < kConsentDisplayActive[mid].first) hi = mid;")
out.append("    else if (scalar > kConsentDisplayActive[mid].last) lo = mid + 1;")
out.append("    else return true;")
out.append("  }")
out.append("  return false;")
out.append("}")
out.append("}  // namespace biv::cli")
sys.stdout.write("\n".join(out) + "\n")
